[package]
name                   = "tach"
version                = "0.1.0"
edition                = "2024"
license                = "MIT"
authors                = ["katelyn martin <git@katelyn.world>"]
description            = "a compact cpu monitor"

[dependencies]
crossterm = "0.29"
